### ISSUE TITLE
ValueError: AYG contains at least one non nucleotide or N character

### ISSUE THREAD

**Issue by Razi1026** [silastittes/cds_fold#3]
Hello,

I ran cds_fold script on my data: 
python cds_fold.py -o sitefold.txt file.fasta file.gff > reference.log

I got this error:

File "cds_fold.py", line 180, in <module>
    gene_folds = n_fold(c_sequence, old_name)
  File "cds_fold.py", line 81, in n_fold
    return [len(set(condon(seq[i:i+3], j))) for i in range(0, len(seq), 3) for j in [1,2,3]]
  File "cds_fold.py", line 81, in <listcomp>
    return [len(set(condon(seq[i:i+3], j))) for i in range(0, len(seq), 3) for j in [1,2,3]]
  File "cds_fold.py", line 71, in condon
    if pos == 1: return [translate(b + seq[1:]) for b in ["A", "T", "G", "C"]]
  File "cds_fold.py", line 71, in <listcomp>
    if pos == 1: return [translate(b + seq[1:]) for b in ["A", "T", "G", "C"]]
  File "cds_fold.py", line 33, in translate
    raise ValueError(f'{seq} contains at least one non nucleotide or N character')
ValueError: AYG contains at least one non nucleotide or N character

Would you please help me to solve this error? 
Thanks

**Comment by silastittes** [comment]
Hi There! 
I believe this error message is from a slightly older version of the code. I recently relaxed this to print a warning instead of an error.  

While inside your local version of `cds_fold`, could you run 

```
git pull
```
and try your command again?

Hope this helps! Happy to continue to help troubleshoot.

**Comment by Razi1026** [comment]
Hi,

Thanks for your guide. I downloaded new current version(download zip) here and I ran it.

This time it run around 30 mins and then stops by below error without "sitefold.txt", but there is "reference.log":

Traceback (most recent call last):
  File "cds_fold.py", line 196, in <module>
    c_sequence = build_seq(c_sequence, seqid, start, end, strand)
  File "cds_fold.py", line 86, in build_seq
    c_seq = fasta_dict[seqid].seq[start-1:end]
KeyError: 'ChrC'

Would you please help on this? (I have both ref.dict and ref.fai files there)

Thank you very much!

**Comment by silastittes** [comment]
Progress! 
This error message isn't helpful, so my apologies for that. I'll open an issue to remind myself to improve how this type of problem is handled. 
This error is almost certainly happening because 'ChrC' appears in your gff file but not in your fasta file. Is it possible that sequence is missing or the names that appear in the fasta file are slightly different than the gff file (uppercase/lowercase missing "_", etc.)?

There are a bunch of ways to check for this, but for this particular case I would do 

```
grep -c "ChrC" file.fasta 
grep -c "ChrC" file.gff
```
My guess is, the first command will return 0. If so, two quick fixes would be 
1. filter the gff to only include sequence present in the fasta
2. edit the fasta to ensure the sequence names match the gff

Hope this helps!

**Comment by Razi1026** [comment]
I did this:

grep -c "ChrC" file.fasta 
0
grep -c "ChrC" file.gff
620

Then I filtered gff file!

Problem **SOLVED!!**

Thank you very much!

**Comment by silastittes** [comment]
Great! Thanks for giving the software a try, and for bringing the issue to my attention. Gonna close this issue, but feel free to reopen if similar problems crop up, or open another issue if something else goes wrong.
